Revert "vndservicemanager: remove static dependency on libselinux"
MAC builds have the following compile error:

Undefined symbols for architecture x86_64:
  "_selabel_file_init", referenced from:
      _initfuncs in label.o
ld: symbol(s) not found for architecture x86_64
clang.real: error: linker command failed with exit code 1 (use -v to see invocation)

Reverting patchset.

This reverts commit 34a5f40cd21f6b4edb38fc3bb7bbd9c0dc593e2a.

Change-Id: I8ab4a14ad853a1bf13412a13371661a859a73df7